### ISSUE TITLE
Babel has great implementations of const and let

### ISSUE THREAD

**Issue by scottrippey** [gocardless/javascript-style-guide#6]
I love this style guide -- especially the ES6 section -- and I'm going to adopt it as my own.
I just had a comment about your use of `const` and `let` ... I assume that section is outdated, because Babel (formerly 6to5) now has great support for them.

Examples:
### Const:
```
const c = 5;
c = 10;
```
> `Error: "c" is read-only`

### Let:
```
let i = 0;
for (let i = 0; i < 10; i++) {
  console.log(i);
}
for (let i = 0; i < 10; i++) {
  console.log(function(){ return i; });
}
```

Compiled output:
```
"use strict";

var i = 0;
for (var _i = 0; _i < 10; _i++) {
  console.log(_i);
}
for (var _i2 = 0; _i2 < 10; _i2++) {
  (function (_i2) {
    console.log(function () {
      return _i2;
    });
  })(_i2);
}
```

**Comment by harrison** [comment]
Great to hear! We are trying to figure out where the angular community goes with TypeScript at the moment and holding off a bit on changing to babel just yet. Internally we have a bunch of very Traceur specific build tools..

**Comment by harrison** [comment]
Worth mentioning babel is a great tool and would totally recommend it over Traceur if those where your choices.

**Comment by jackfranklin** [comment]
@scottrippey thanks for this - as @harrison we've got a lot of internal Traceur specific tools and we're unsure if it's worth the effort to move, given that we're going to be moving to Angular 2 and it might be worth focusing more on TypeScript and converting to that. We'll update the guide when we've got it figured out.

**Comment by thejameskyle** [comment]
Hi @jackfranklin and @harrison, Babel contributor here! While TypeScript is going to be used to implement Angular internally, for many users Babel will be the better choice as most people have no need for types and Babel is much more strict about ES6+ spec compliancy. We (the Babel team) were actually just with the Angular team the other day talking about Babel in the Angular community.

Let me know if you guys have any questions or you can always swing by our support chat https://gitter.im/babel/babel
